import type { ThemeConfig } from 'antd'

export const themeTokens = {
  bg: '#FFFFFF',
  surface: '#FFFFFF',
  surfaceMuted: '#FAFAFA',
  border: '#E5E7EB',
  divider: '#F3F4F6',
  text: '#0F172A',
  textMuted: '#6B7280',
  textFaint: '#9CA3AF',
  primary: '#1677FF',
  primaryHover: '#4096FF',
  primarySoft: '#EFF6FF',
  success: '#10B981',
  danger: '#EF4444',
  warning: '#F59E0B',
  radiusCard: 8,
  radiusButton: 6,
  shadowCard: 'none',
} as const

const antdTheme: ThemeConfig = {
  token: {
    colorPrimary: themeTokens.primary,
    colorPrimaryHover: themeTokens.primaryHover,
    colorSuccess: themeTokens.success,
    colorWarning: themeTokens.warning,
    colorError: themeTokens.danger,
    colorInfo: themeTokens.primary,
    colorBgBase: themeTokens.bg,
    colorBgLayout: themeTokens.bg,
    colorBgContainer: themeTokens.surface,
    colorBgElevated: themeTokens.surface,
    colorFillSecondary: themeTokens.surfaceMuted,
    colorBorder: themeTokens.border,
    colorBorderSecondary: themeTokens.divider,
    colorSplit: themeTokens.divider,
    colorText: themeTokens.text,
    colorTextSecondary: themeTokens.textMuted,
    colorTextTertiary: themeTokens.textFaint,
    borderRadius: themeTokens.radiusButton,
    borderRadiusLG: themeTokens.radiusCard,
    boxShadow: themeTokens.shadowCard,
    boxShadowSecondary: themeTokens.shadowCard,
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans SC', sans-serif",
    fontSize: 14,
    fontSizeSM: 13,
    fontSizeLG: 16,
    lineHeight: 1.5,
    lineHeightHeading1: 1.25,
    lineHeightHeading2: 1.25,
    lineHeightHeading3: 1.25,
    lineHeightHeading4: 1.25,
    lineHeightHeading5: 1.25,
    controlHeight: 32,
    controlHeightSM: 24,
    paddingLG: 24,
    paddingMD: 16,
    paddingSM: 12,
    paddingXS: 8,
    marginLG: 24,
    marginMD: 16,
    marginSM: 12,
    marginXS: 8,
  },
  components: {
    Layout: {
      headerBg: themeTokens.surface,
      bodyBg: themeTokens.bg,
      siderBg: themeTokens.surfaceMuted,
    },
    Card: {
      paddingLG: 24,
      paddingMD: 24,
      colorBorderSecondary: themeTokens.border,
      boxShadow: themeTokens.shadowCard,
    },
    Table: {
      headerBg: themeTokens.surfaceMuted,
      headerColor: themeTokens.textMuted,
      headerBorderRadius: themeTokens.radiusCard,
      rowHoverBg: themeTokens.surfaceMuted,
      borderColor: themeTokens.divider,
    },
    Menu: {
      itemColor: themeTokens.textMuted,
      itemSelectedColor: themeTokens.text,
      itemHoverColor: themeTokens.text,
      itemHoverBg: 'transparent',
      itemSelectedBg: 'transparent',
      itemActiveBg: 'transparent',
      horizontalItemSelectedColor: themeTokens.text,
      horizontalItemHoverColor: themeTokens.text,
      horizontalItemBorderRadius: 0,
    },
    Button: {
      borderRadius: themeTokens.radiusButton,
      fontWeight: 500,
      boxShadow: 'none',
      primaryShadow: 'none',
      defaultShadow: 'none',
      defaultBorderColor: themeTokens.border,
      defaultColor: themeTokens.text,
    },
    Input: {
      colorBorder: themeTokens.border,
      activeBorderColor: themeTokens.primary,
      hoverBorderColor: themeTokens.primaryHover,
      colorBgContainer: themeTokens.surface,
      activeShadow: 'none',
    },
    Select: {
      colorBorder: themeTokens.border,
      optionSelectedBg: themeTokens.primarySoft,
      activeBorderColor: themeTokens.primary,
      hoverBorderColor: themeTokens.primaryHover,
      activeOutlineColor: 'transparent',
    },
    Tag: {
      colorBorder: themeTokens.border,
    },
    Tooltip: {
      colorBgSpotlight: themeTokens.text,
    },
    Modal: {
      headerBg: themeTokens.surface,
      contentBg: themeTokens.surface,
      boxShadow: 'none',
    },
    Tabs: {
      inkBarColor: themeTokens.primary,
      itemSelectedColor: themeTokens.text,
      itemHoverColor: themeTokens.text,
    },
  },
}

export default antdTheme
